apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  labels:
    app: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: shopping:v.46
        imagePullPolicy: Always
        ports:
        - containerPort: 8282   # container port your app exposes
