apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping-app
  ports:
    - protocol: TCP
      port: 80           # cluster-internal service port
      targetPort: 8282   # maps to containerPort in Deployment
      nodePort: 30036    # external access port on node
